### ISSUE TITLE
Declare firm milestones for matching planning w/ execution

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#1]
e.g., demo to collabs

This should perhaps be part of viz.yaml where other declarative items live.

**Comment by jread-usgs** [comment]
maybe README? issue milestones? other? Some of us have other opinions on this.

**Comment by aappling-usgs** [comment]
In practice, sprint vizzies leave no room or need for formal milestones, and for longer vizzies, GitHub issues and milestones and project leads have been sufficient to keep us on track.
