### ISSUE TITLE
Create sandbox to work with figures and interactions separate from rest of viz

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#10]
Generate a sandbox for each figure/tag combination to be able to work with figures as they would be in app without having gone through the layout process to get them into the final viz.

**Comment by aappling-usgs** [comment]
In recent vizzies we have become better at trying out figures and layouts without this sandbox; I think we can close this issue for now. If the need and will arises again later, we can create a sandbox then.
