### ISSUE TITLE
make fails unless make clean is run

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#115]
call function script doesnt get copied over unless you do `make clean`.

**Comment by aappling-usgs** [comment]
hmm, i wonder why this isn't getting run early on: https://github.com/USGS-VIZLAB/vizlab/blob/debaf3935111b61f449e67b3c39349cb521e1f7f/R/createMakefiles.R#L179

**Comment by aappling-usgs** [comment]
just got two confirmations from folks for whom this was a problem (callFunction() didn't get copied) even though they called `createMakefiles` first.
