### ISSUE TITLE
bug with different R versions

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#117]
This is odd and just trying to capture it here

Marty had an old vizlab pkg on 3.2.5, the updated to v3.3.2. 

Getting this issue
```
Error in process.treemap(viz) : could not find function "readDepends"
Calls: do.call ... <Anonymous> -> process.character -> process -> process.treemap
Execution halted
```

So, this function is available in the version of vizlab he has on 3.3, but not 3.2. I deleted the vizlab package in his libpath for v3.2, and it worked!

this is odd and might be hard to reproduce

**Comment by jread-usgs** [comment]
@aappling-usgs this make any sense to you?

**Comment by aappling-usgs** [comment]
Nope, none!

**Comment by jread-usgs** [comment]
I meant my explanation of it. Any questions?

**Comment by aappling-usgs** [comment]
Hmm. Well, I think I understand what you wrote, though still looks super hard to debug. Can you narrow it to a more direct call to `readDepends`, bypassing `process` and `make`? Is it possible that the older version of vizlab doesn't automatically load the vizlab project before running scripts, while the new one does?

**Comment by jiwalker-usgs** [comment]
I think the profile.yaml that sets the environment vars for the makefiles needs to be updated anytime R is updated.  It is probably just in a weird state due to that.  We should probably document that more clearly.

**Comment by aappling-usgs** [comment]
that's possible, good idea. though i still don't understand why the viz would suddenly start to work once you delete the old package and without changing anything else (e.g., pointing to the new R in profile.yaml)

**Comment by aappling-usgs** [comment]
could we add a check in createMakefiles() that offers to update your profile.yaml for you? because everybody runs createMakefiles() at the start of a new vizzie, right? so it could be a good place to remind people to check.

**Comment by jiwalker-usgs** [comment]
Yeah, that is probably a reasonable place to check for that.

**Comment by aappling-usgs** [comment]
closing this issue because marty's problem was surely resolved by now. spun off the proposed check into #260
