### ISSUE TITLE
Automate R dependencies (3)

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#123]
I'm not seeing this issue...sorry if it's up already. This would be useful for the users (at least a check and notify function at a minimum). Also, for the Jenkin's job...if someone checks in a script with a new R package dependencies...it would be great if the Jenkin's job had the ability to automatically detect that and install if necessary.

**Comment by eread-usgs** [comment]
- [ ] Verify then install missing
- [ ] Happens every time make is run
- [ ] Should have CRAN, GRAN, Github capabilities (others?) 
- [ ] Modify viz.yaml structure if necessary 
- [ ] Include version but don't enforce it- make a message on verify, e.g., "You have version 2, they use version 1.6"

**Comment by aappling-usgs** [comment]
This issue is the newest expression of ideas in https://github.com/USGS-VIZLAB/vizlab/pull/106 and https://github.com/USGS-VIZLAB/vizlab/issues/91
