### ISSUE TITLE
Publish landing page

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#124]
I think it still needs some love. 
- [x] not finding microplastic and fish thumbnails. 
- [x] not getting the water-use viz
- [x] doesn't have the CO or CA viz's
- [x] follow style of owi.usgs.gov (banner / footer)?
- [x] should it be baked into a production build? Or, it's own Jenkin's job?
- [ ] does it need a basic RSS feed?
- [ ] search or tag feature?
- [x] publishLandingPage needs to use thumbnail path from viz.yaml
- [ ] favicon 

![image](https://cloud.githubusercontent.com/assets/1105215/20904231/472391a2-bb04-11e6-8640-c49c56d4d4b2.png)

**Comment by mwernimont** [comment]
Huh, I added the header footer into the code with #113, so its weird its not there.

@jiwalker-usgs didn't we talk about those images not showing up? Something about relative links, so they will show up fine live?

**Comment by jiwalker-usgs** [comment]
yeah, they will work if you deploy everything to the same contexts, so that everything is relative to owi.usgs.gov/vizlab.  We can rethink that if it is a problem.

**Comment by ldecicco-USGS** [comment]
I'll set up a job to deploy to dev right now, then we can talk...

**Comment by jiwalker-usgs** [comment]
Sounds good :+1:

**Comment by lindsaycarr** [comment]
can we close #50 then?

**Comment by ldecicco-USGS** [comment]
I *knew* there had to be an issue, not sure why I couldn't find it. Looks like there's only 1 lingering box there that isn't included here...I'll add that and close the other.

**Comment by lindsaycarr** [comment]
#131 and #130 (plus PRs in the other viz repos that say `thumbnail-landing` or something similar) fix some of these landing page issues.

**Comment by aappling-usgs** [comment]
remaining tasks/ideas are now in their own issues at #253 and #254, so this issue can be closed
