### ISSUE TITLE
storeSBcreds should keep password hidden

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#125]
Change to the way authenticate:

https://github.com/USGS-R/sbtools/blob/master/R/authenticate_sb.R#L59

does log in, so we don't have to see our passwords show up on the screen.

**Comment by lindsaycarr** [comment]
Also for windows users, it is saving it in a diff location than it is trying to read it. Just had to copy it into the other directory. Similar to #81

**Comment by aappling-usgs** [comment]
i'd really like to see storeSBcreds removed in conjunction with repointing `authRemote` to `dssecrets` a la #205.
