### ISSUE TITLE
add retina favico

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#136]
Favicos for retina at different resolutions are supported and I think we should include this as part of the favico export.

**Comment by jread-usgs** [comment]
retina vs non-retina:
![image](https://cloud.githubusercontent.com/assets/2349007/21290747/02b546a0-c48c-11e6-96d1-50c4332a51f2.png)

**Comment by aappling-usgs** [comment]
duplicated by #222
