### ISSUE TITLE
Define USGS and OWI

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#138]
In header and or footer...we need to spell out U.S. Geological Survey at least once..

**Comment by aappling-usgs** [comment]
@ldecicco-USGS , the landing page now spells out U.S. Geological Survey in the footer, and clicking on the USGS link in the header takes you to a spelled-out version. OWI (soon IIDD - see #255) is not spelled out on that page but is defined when you click on the OWI logo. 

What do you think - good enough, or do we need more?

**Comment by ldecicco-USGS** [comment]
Yup, there's some requirement that there needs to be "U.S. Geological Survey" on the page once, so in the footer is good enough.

**Comment by aappling-usgs** [comment]
Cool. What about for individual vizzies? Looks like we usually end up writing "U.S. Geological Survey" somewhere in the caption - just confirmed for maria, irma, harvey, water use, and walleye-bass - but there's no guarantee. Should we pop that in the default viz footer, or does the requirement only apply to landing pages?

**Comment by ldecicco-USGS** [comment]
No, that (was at least...) a USGS-wide requirement. I use to be able to find the requirements here:

http://communities.usgs.gov/blogs/vis/
or
https://www2.usgs.gov/usgs-manual/500/550-1.html

but not seeing it quickly. Maybe someone from Emily's branch can remind us where all that info is.

**Comment by aappling-usgs** [comment]
Thanks. OK, let's assume it's required for all viz pages - i'll make a new issue for adding it to the footer so we don't have to think about it again
