### ISSUE TITLE
Thumbnails - research (1)

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#141]
- [ ] Specify standard sizes (FB, Twitter, our landing page)

- [ ] Get Thumbnail for our landing page

- [ ] OTher issues?

**Comment by eread-usgs** [comment]
We need a target thumbnail size b/c twitter , FB have different rules. Force compliance on size.

Consider: Make sure landing page thumbnail sizes are compatible.

**Comment by eread-usgs** [comment]
Check file size and pixel dimensions - max and min?

**Comment by wdwatkins** [comment]
https://developers.facebook.com/docs/sharing/best-practices

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

https://dev.twitter.com/cards/types/summary-large-image
> Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size.

**Comment by wdwatkins** [comment]
biggest image that would fit twitter is a little under 600x600 px, which isn't ideal for facebook.

Read about pixels here: http://shutha.org/node/796

**Comment by wdwatkins** [comment]
@jiwalker-usgs should a publisher for this do anything with the cards in the html?  Or just check the dimensions?

**Comment by jiwalker-usgs** [comment]
I think the publisher will mostly be moving files around and deciding on naming, but it would be useful to include "compliance" as part of that to verify that images meet the specs.
