### ISSUE TITLE
Add key documentation to Readme.

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#142]
-[ ] Overall overview of package in Readme, so user doesnt need to go to documentation. (to jog your memory, this was a request @dblodgett made during the Water User retro)

-[ ] Nice to have: make functions that help users understand how to use. Function might be called 'describe' , e.g., describe(fetch). Instead of help, would give you possible fields that could be included in argument.

**Comment by eread-usgs** [comment]
- [ ]

**Comment by aappling-usgs** [comment]
What if we published the vignettes as github.io pages and put a link on the readme?
