### ISSUE TITLE
Spin up test tier (2)

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#143]
Per discussion at Water Use viz. Would be nice to test changes before pushing to prod.

**Comment by eread-usgs** [comment]
make it public so reviewers and partners can access.

**Comment by eread-usgs** [comment]
We already have test bucket. At one point this was not view-able to internal USGS- need to check this with CHS.

**Comment by ldecicco-USGS** [comment]
We have this tier, and have requested that it be publicly accessible. That may or may not happen, either way it's out of my personal control.
