### ISSUE TITLE
Common tasks for each viz- create issues for these at the outset of each new viz (2)

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#144]
Use github API to automate creation of these issues?

- [ ] Social media checklist
- [ ] Reviewer checklist
- [ ] Thumbnail
- [ ] Verify thumbnail dimensions and resolution rules through developer documentation
- [ ] Related content
- [ ]  Press release

**Comment by eread-usgs** [comment]
Make an init that is part of the skeleton- only gets run once.

**Comment by lindsaycarr** [comment]
@eread-usgs what is the checklist for reviewers?

**Comment by lindsaycarr** [comment]
@eread-usgs @jiwalker-usgs also wondering what labels would be good to have? outreach, publisher, visualizer, reader, fetcher, UI ?
