### ISSUE TITLE
'Review' for viz.yaml

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#149]

**Comment by eread-usgs** [comment]
Add 'review' to viz.yaml, includes the review plan, include documents in the repo we could link to. Include dates to go to test, other parts of the timeline. Social medial plan.

**Comment by jiwalker-usgs** [comment]
This issue came from a comment I had for insight into review schedule within the repo, but I think adding more to viz.yaml at this time is unnecessary.
