### ISSUE TITLE
Social media buttons

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#161]

**Comment by eread-usgs** [comment]
![screen shot 2017-02-28 at 3 56 01 pm](https://cloud.githubusercontent.com/assets/7794368/23435960/70f8f258-fdce-11e6-8ab0-dbe630217291.png)

**Comment by eread-usgs** [comment]
something like this (above) from here: https://howmuch.net/articles/most-least-expensive-universities-in-usa

**Comment by eread-usgs** [comment]
We want the buttons to stay at the top of the page while scrolling, and have them vertically stacked.

**Comment by eread-usgs** [comment]
And, the embed button should show up here too.

**Comment by jiwalker-usgs** [comment]
We will want to bring functionality from gages-through-ages to vizlab for use more commonly.

**Comment by aappling-usgs** [comment]
should be able to opt in or opt out (e.g., google-analytics wouldn't want these buttons)

**Comment by aappling-usgs** [comment]
TO DO:
- [ ] we need a publisher for social media that can pick up the required URLs for linking to facebook, twitter, and github.
- [ ] still working on placement for the icons from usability/prettiness perspectives, especially for mobile. do we want it just horizontal, or want ability to make it vertical on some of them? two different style sheets could give us a lot of flexibility here.

TABLED:
* reddit - no idea how this would work yet. tabling this one for now. where would it link? would each user who clicks on the icon be able to generate their own reddit post? ideally this would provide a link to an existing reddit on which you could post.
