### ISSUE TITLE
use the svginject javascript library

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#187]
problems with getting twitter to pick up a tweet/card can be partly addressed by using the svginject javascript library, which would reduce page size. the library tells the client that svg is there, without actually loading it until needed

**Comment by jiwalker-usgs** [comment]
svg-inject allows a png fallback, we may want to consider supporting that.

**Comment by aappling-usgs** [comment]
all implemented on @jiwalker-usgs 's computer, just needs testing

**Comment by aappling-usgs** [comment]
need laura's PR merged for the example to build, need alison's PR merged to check for conflicts

**Comment by jiwalker-usgs** [comment]
#218 changes how SVGs work
