### ISSUE TITLE
Current footer work

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#189]
- [x] Make layout more like water-use (lose the current footer templated text, but keep "Contact Us", and change "The code used here is available on github" to "Get the Code"
 - [ ] Remove thumbnails on mobile (?), at least work on mobile
 - [ ] double-check styles (esp fonts)

**Comment by mwernimont** [comment]
The footer needs a few touchups after viewing it locally with irma, but its in a good enough place where i can move onto the next ticket before I need to tweak

**Comment by aappling-usgs** [comment]
does "good enough place" reflect the contribution of https://github.com/USGS-VIZLAB/vizlab/pull/210?

is it still true that these two items remain?
 - [ ] Remove thumbnails on mobile (?), at least work on mobile
 - [ ] double-check styles (esp fonts)

**Comment by mwernimont** [comment]
Well the thumbnails don't seem to work at all for the vizzies, but I have the code working for mobile, so I don't know if we need to remove them from mobile.  And style is something I would like someone else to check off.

**Comment by aappling-usgs** [comment]
looking good for Maria!
