### ISSUE TITLE
make publish.resource aware of figure embed

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#197]
Had to change filepath for resources when publishing the embedded figure. @jiwalker-usgs wants to do this in a better way than in #198 which is a bandaid for hurricane-irma viz to work with embed.

**Comment by ldecicco-USGS** [comment]
OOOOOOOOOO K
I sort of see what was happening. Something to do with the path needing 1 vs 2 dots (to get the paths to the libs correct).

In the "example" viz, I've done this:
```
    id: embed-page
     name: embed-dots
     publisher: page
     template: embed
     mimetype: text/html
     depends: ["dots_section", "svg-css", "lib-jquery-js", "lib-vizlab-javascript","lib-svg-injector-js", 
       "lib-vizlab-favicon", "lib-social-media-css","lib-d3-js","lib-tooltip-js"]
     context:
       resources: ["svg-css", "lib-jquery-js", "lib-svg-injector-js", "lib-vizlab-javascript",
         "lib-vizlab-favicon", "lib-social-media-css","lib-d3-js","lib-tooltip-js"]
       embed: ["dots_section"]
```
as well as including a more top level `embed: TRUE` (so, to both go in and out of that `if` statement that Lindsay linked to as the band-aid solution)

Both seemed to work....
So....
I'd vote we keep this issue open, but not have it as a "High Priority" for this project.

**Comment by aappling-usgs** [comment]
Laura did a bunch of work on embed that maybe sorta fixes this. The exact line Lindsay mentioned remains, but we're content now.
