### ISSUE TITLE
Footer vizlab functional issues

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#202]
- [x] Path to vizzy thumbnails fixed
 - [x]  Need a way to over-ride arguments easily (for example, thumbnail url)
 - [ ] Optional "last updated" field

**Comment by ldecicco-USGS** [comment]
#212 Fixes the first 2 above.

**Comment by aappling-usgs** [comment]
last item getting tabled for now:
- [ ] Optional "last updated" field
