### ISSUE TITLE
dependency diagram

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#204]
could add an automatic regeneration of the diagram into the travis build? so far the solutions i've found are for linux

**Comment by ldecicco-USGS** [comment]
I've used `Diagrammr` a bit, it's not too hard to use

**Comment by aappling-usgs** [comment]
cool. yeah, looks nice. trick is to great the data structure that can be diagrammed.

**Comment by aappling-usgs** [comment]
For easier issue searching: dependency diagram = dependency graph = target tree

**Comment by aappling-usgs** [comment]
In Irma/Maria retro, someone wrote, "Need more intuitive page component traceability throughout the vizlab project, but especially in the visualize step." Will a dependency diagram meet this need? If not, what else would be useful?

**Comment by aappling-usgs** [comment]
sam can review

**Comment by aappling-usgs** [comment]
fun way to do this, maybe, would be to write a travis CI job that would build the diagram and push that result to the PR, or the README, or the github-io page, or something.

but a much simpler, local function would also be just fine - up to you.

**Comment by aappling-usgs** [comment]
```r
remake::diagram(remake_file='remake.yaml')
```
gives this for USGS-VIZLAB/example:
![image](https://user-images.githubusercontent.com/12039957/31971921-e4d5592c-b8d2-11e7-8b80-95514f652875.png)

**Comment by aappling-usgs** [comment]
Closing because `remake::diagram` is pretty good and remake is pretty nearly complete as of #316
