### ISSUE TITLE
makefile details change randomly

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#209]
I must have some other profile.yaml lying around that keeps getting called that references an old R version. Frequently, when I run `make ___`  from the command line, the details of that make file are changed (e.g. if I run `make publish` and go back and look at `publish.make` the R version is now pointing to an old one). My current work around is to just re-run `createMakefiles()` when I notice this happens, everything is reset, and I can continue. It's caused some headaches though. This is probably just a snowflake case on my computer, but I wanted to record it somewhere to be addressed later and in case someone else started having the same issue.

We discussed this via Slack at first, and @aappling-usgs suggested that it might be changing if I switch between running `make` in the command line vs clicking `build` in RStudio. While a promising suggestion, I have solely switched to `make` via command line over the last few days and still see it occurring. 

{would like to look into this after hurricane-irma & vizlab sprints}

**Comment by aappling-usgs** [comment]
Thanks for laying out the details so clearly, Lindsay. As groundwork for more debugging (yes, after the sprints), could you run a search for `profile.yaml` on your computer? Searching within C:\Users\username should be sufficient. You can ignore shortcuts and anything in a vizlab\testviz folder. For example, on my computer I see 8 shortcuts (2 under Recent/Recent Items, and 6 with the IE logo) and 2 testviz files (from installations of the vizlab package), and then exactly these two remaining profile.yaml files:

C:\Users\username\.vizlab\profile.yaml
C:\Users\username\My Documents\.vizlab\profile.yaml

**Comment by aappling-usgs** [comment]
this is resolved by #246
