### ISSUE TITLE
read.shp

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#240]
already implemented at https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/read/read.shp.R, just need to check it over and add it to vizlab once it's sufficiently general for our needs

**Comment by jzwart** [comment]
Are all shape files going to be stored in a zip folder? Current code unzips before reading but that could be specific to Hurricane Maria viz `unzip(viz[['location']], exdir = shp.path)`
Otherwise could make function check if in zipped folder or not before reading.

**Comment by aappling-usgs** [comment]
Good question. It's encouraged for each viz item to correspond a single file, and remake will make this even more important (except for R objects, which will never have data type shp). So i thiiink we can pretty safely require a zip file here.

**Comment by jzwart** [comment]
OK sounds good.

**Comment by aappling-usgs** [comment]
Side note: I see that the starter code from Maria has 2 arguments to the function. The generic `readData` only accepts a single argument, `viz`, and this method will need to match that. If `idx` is necessary for this vizlab version of the function (i just haven't thought about it so don't know), it should be passed as a required component of the viz item. and example would be `view-limits-mobile` in Maria:

`bbox` is defined in the viz.yaml item: https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/viz.yaml#L151-L159

`bbox` gets retrieved and used within `fetch.view_limits()` like this: https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/fetch.view_limits.R#L2

and still better is to add a check to the reader to make sure that argument exists in the viz item, as was done here for `fetch.hurricaneTrack()`: https://github.com/USGS-VIZLAB/hurricane-maria/blob/master/scripts/fetch/hurricaneTrack.R#L21-L22

**Comment by jzwart** [comment]
Got it. Yup I see that the readers all have checks for required inputs. I'll put them in.

**Comment by jread-usgs** [comment]
Another side note - we probably shouldn't use "index" of the layers, we should instead have some way of specifying the actual layer (if supporting reading a specific layer from a shapefile that includes multiple). Assuming index order seems fragile. 

But, we'd probably want to use some kind of regex on the layer naming, since we often don't know the exact name and instead know the pattern the name is expected to have.
