### ISSUE TITLE
let hoverText handle multiple svgs on a page

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#273]
See discussion at https://github.com/USGS-VIZLAB/vizlab/pull/272#discussion_r144186153 - right now tooltip.js won't work with multiple svgs, which is fine for some vizzies but could eventually bite us.

**Comment by jread-usgs** [comment]
ha! was just going to create this issue.

**Comment by jread-usgs** [comment]
There are at least two parts of the code that make dealing with multiple svgs a challenge:

1. we use the `svg` to get the coordinates of the mouse, and deal w/ the fact that the svg may be scaled in different ways. We also use this to get the bounds of the svg viewBox. 
2. we have one id for the tooltip group, which would need to be unique per svg, or have some way of sharing (such as using html tooltips which sit elsewhere in the DOM).

**Comment by jread-usgs** [comment]
The way [active flood](https://github.com/USGS-VIZLAB/active-flood-viz/blob/8b25ab4b90dfe51defaebf0ee038112305c4332b/floodviz/static/js/hydrograph.js#L356)  dealt with this was to include a lot more parameters in the tooltip function, and have the function itself do less work to figure out things like the viewBox. I don't think I did enough testing to see if this approach was robust against scaling the svg (and therefore, changing the meaning of the pixel space passed to the function).

**Comment by jread-usgs** [comment]
seems simple solution is to use `evt.target.ownerSVGElement;` to get access to the parent svg that the event is coming from. This way we can reference id selection from that svg and deal with both of the issues mentioned above (i.e., it doesn't matter if the same tooltip id is used across multiple ids, and we have a way of accessing the `viewBox`)
