### ISSUE TITLE
switch to safer password storage [1.5]

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#29]
profile & password info is currently in user/local and depends on .gitignore to never commit that info to the repository. something safer (storing password files outside the repo, for starters) would be great.

**Comment by eread-usgs** [comment]
Just for SB, there is an authenticateSB script, that's in the repo but not checked in. We want to make an external.vizlab folder that can contain this and cross project, not be checked in. With this we should avoid clear text passwords, by encryption. 

Encryption would be nice to have, main priority is to get it out of the repo. 

If we are running this on a dev server with CI, need a way to set the pw into its environment.

**Comment by wdwatkins** [comment]
Are we ok with introducing a new package dependency for encryption?  `digest` seems to be an option.

**Comment by jiwalker-usgs** [comment]
I'd be ok bringing in `digest`

**Comment by eread-usgs** [comment]
- [ ] update  documentation

- [ ] check in the fetch from auth remote file to see if there's an active sb session

**Comment by wdwatkins** [comment]
#64 should finish this.
