### ISSUE TITLE
make or remake files for publish

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#31]
we need some sort of remake or make file for the layout, ideally in conjunction with definitions of `getFigureInfo`, `googleAnalyticsId`, `buildPages`, `buildJS`, `runAll`, etc. that are built into vizlab

this issue is a spin-off from #5.

**Comment by jread-usgs** [comment]
was `make or remake files for layout`. Updated

**Comment by aappling-usgs** [comment]
updated to what?

**Comment by jread-usgs** [comment]
Updated the title, but apparently it didn't save...fixed now

**Comment by jiwalker-usgs** [comment]
This should be covered by #37 when merged

**Comment by jiwalker-usgs** [comment]
Going to close this, though we should create new issues for problems encountered with publishing.
