### ISSUE TITLE
support a `missing` method for `as.viz`?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/vizlab#315]
I have run into this a few times where we change ids and function names. We are also on a path to converge on a style guide for ids and functions. 

I see this a lot:
```r
fetch.{thing} <- function(viz = as.viz("{thing}"){ 
   ...
}
```
it seems to happen often that we change ids and then don't change the default arg to the function to reflect this. And then this only becomes clear (and is confusing) when debugging. 

Given our pivot to remake, should we 1) get rid of this practice and go with `fetch.{thing} <- function(viz)`, or 2) support a generic `missing` method for `viz` in this case that uses the function name. 

such as:
```r
fetch.viewbox_limits <- function(viz){
  if (missing(viz)){
    func_name <- as.character(match.call()[[1L]])
    id <- tail(strsplit(func_name, "[.]")[[1L]], 1L)
    viz <- as.viz(id) 
  }
...
```
This is kind of ugly, and I don't think I like it. But I figured I would ask the question either way.

**Comment by aappling-usgs** [comment]
Hmm, I guess we do change viz item names often enough to make this a problem, don't we?

For solutions, I prefer option 1 to option 2. Vizlab has changed a lot, such that we can actually already call
```r
fetch('thing')
```
without a default for `fetch.thingfetcher`'s viz argument. attempting to fetch a non-viz-item gives an error, albeit not one that's extremely explicit about the viz id not existing:
```r
> fetch('notathing')
Error in match(no.match, c(`NA` = NA, stop = stop("Could not find ", x))) : 
  Could not find notathing
```

I'm personally content with this behavior (along with a team decision to stop using the `viz=as.viz()` default). What do you think - good enough?

**Comment by jread-usgs** [comment]
"along with a team decision to stop using the viz=as.viz() default" 
yes, I think w/ `remake` and this update to the guidelines that option 1 is the way to go. 
Safe to close this issue?
