### ISSUE TITLE
Text has no margin

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#342]
See water-use-15 or run the example.

Can we get the text to default to a normal looking margin (ie...some space between the edge of the browser and the text...so it doesn't look like this:)

![image](https://user-images.githubusercontent.com/1105215/37004243-63825c6e-2095-11e8-9169-f9c8e59ce5e0.png)

**Comment by aappling-usgs** [comment]
laura suggests in https://github.com/USGS-VIZLAB/vizlab/pull/349#issuecomment-373123818:

Can you add a div in printAll with some style?

perhaps:
```
<div id="{{id}}">
  <div class="textContentAligner">
    <p>
      {{{ text }}}
    </p>
  </div>
</div>
```
and in content:
```
.textContentAligner{
  padding:0 10px;
}
```

**Comment by aappling-usgs** [comment]
Why two different divs in printall.mustache, @ldecicco-USGS ? Could those be consolidated into
```
<div id="{{id}}" class="textContentAligner">
  <p>
    {{{ text }}}
  </p>
</div>
```
?
(i'm not speaking from expertise, just want to understand)

**Comment by ldecicco-USGS** [comment]
I was following the "header" template lead I think, but yours looks better!
