### ISSUE TITLE
create content.css

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#348]
This css file should provide default styling for the body/content section of vizzies. This styling will almost certainly include:
* the IE svg scaling fix that we seem to need to add every time: https://github.com/USGS-VIZLAB/water-use-15/commit/47fa7b64263b9c8a3bb2d10a520ee7819a58aff4 (we'll need to make sure there's an `svg` in a tag with id `#content-container`, which might involve additional edits to viz skeleton and/or some additional thinking about how to deal with multi-svg vizzies)
* styling for explanatory text, related to https://github.com/USGS-VIZLAB/vizlab/issues/342
and other features could be added over time as we notice common needs.

Naming: Marty and Alison think that this file should be named `content.css` to pair well with `header.css`, `footer.css`, and any other default formatting files provided by vizlab. Then within a vizzy, we recommend that any overrides to those defaults be placed in a file named `custom.css`, and any svg-specific files be placed in files with names such as `svg.css` (if there's only one svg in the vizzy) or `map.css`, `hydrograph.css`, etc (if there's more than one svg in the vizzy).

**Comment by jread-usgs** [comment]
Since we'd maybe have multiple SVGs in a page, is there a way for the id `#content-container` to be more generic (other than duplicate ids?). Like use a class for that instead?

**Comment by mwernimont** [comment]
.svg-container?

**Comment by ldecicco-USGS** [comment]
Ha, I just started down this path for the "printAll" issues. (I called it "general.css" but "content.css" works too. If @mwernimont wants to take it, super duper, otherwise this afternoon I can keep pushing ahead and trying to get it all working together.

Here's what I copypasted in:
```
.textContentAligner{
  padding:0 10px;
}

/*IE SVG Width Fix*/
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none){
    #content-container svg{
      width:100%;
      height:608px;
    }
}

@media screen and (min-width: 1024px){
  #content-container{
    width:960px;
    margin:0 auto;
  }
  
}

body {
  font-family: sans-serif;
}
```
