### ISSUE TITLE
Accessibility [1]

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-VIZLAB/vizlab#36]
Not sure if vizlab is the place or dinosvg, but would be nice to insert a title by default in all svgs:

https://www.sitepoint.com/tips-accessible-svg/

**Comment by jread-usgs** [comment]
Yeah, it would be `dinosvg` for that
---
Jordan Read, PhD | U.S. Geological Survey | Office of Water Information
608-821-3922 | water • data • science <http://cida.usgs.gov/datascience.html> | g-scholar <https://scholar.google.com/citations?hl=en&user=geFLqWAAAAAJ>

**Comment by eread-usgs** [comment]
We shouldn't violate 508 compliance. 
For svgs:
- [ ]  add title
- [ ]  add text node

**Comment by lindsaycarr** [comment]
Example of adding 508 compliance features for climate-fish-viz:
https://github.com/USGS-VIZLAB/climate-fish-habitat/pull/149
https://github.com/USGS-VIZLAB/climate-fish-habitat/pull/163

SVG: `<object title="">ALT TEXT</object>`
IMG: `<src alt="" title=""></src>`

**Comment by lindsaycarr** [comment]
no script tag is now issue #57; everything else closed in #53
