### ISSUE TITLE
Get an svg in for the header so it's not blurry

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#363]

**Comment by mwernimont** [comment]
So currently the header template is using a SVG https://github.com/USGS-VIZLAB/vizlab/blob/master/inst/resource.library.yaml#L249 . Are we saying it still looks blurry?

**Comment by aappling-usgs** [comment]
ooh, thanks for pointing that out. i wrote this based on a comment in the style doc without checking for myself, but your link is pretty definitive, and i see that it looks fine when i test it now.

**Comment by jread-usgs** [comment]
My screenshot was from an earlier build of this viz. Maybe on an earlier vizlab package? Maybe it was a local build where I didn't have the updated package? Either way, yes, it looks sharp now.
