### ISSUE TITLE
Read- Mime types- Support more file types [3]

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#39]
Read. Support more file types, and more support (to a limited extent), and make more extensible so that people can bring their own files. 

Currently mime types are hard coded, and we only support 5.

**Comment by eread-usgs** [comment]
There are a couple places that mime types are relied upon. So centralizing that in some reasonable way is the preference. Right now Fetch, Read, and Publish all use mime types.

**Comment by eread-usgs** [comment]
@jiwalker-usgs suggests take the mime type dictionary and pull it out into a config file so it's editable by a user of vizlab. Right now the dictionary is a switch statement. 

There is a mime type field in the yaml that specifies mime type.

**Comment by jiwalker-usgs** [comment]
The switch statements that map mimetype to reader and mimetype to publisher should be combined and put in an external file (`inst/etc/mimemap`?).  We should then add this to the skeleton process so each viz has a copy of it that can be modified to add or override mappings that occur.  If this file does not exist in that spot, we can fall back to the `inst/etc/mimemap` or whatever it gets called.

**Comment by eread-usgs** [comment]
- [ ] what to do with zip files- will return a file path, processing step needs to unzip
- [ ] new reader type- readdata.dir for directories. use readR for this. use package mime, function guess type
- [ ] making a lookup table for mime types instead of using the switch statement.

**Comment by jiwalker-usgs** [comment]
fixed with #53
