### ISSUE TITLE
Running CI on PRs (from start)

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#4]
Tie CI into visualization creation from the start, build and deploy with each PR.

**Comment by aappling-usgs** [comment]
Quick feedback would be pretty great. @wdwatkins or @ldecicco-USGS , is this within our reach? Any idea how much effort would be required? How close have we come in recent vizzies?

**Comment by wdwatkins** [comment]
Would be great, but it would have to be a full build every time right?  There wouldn't be any persistent caching between builds?

**Comment by jread-usgs** [comment]
correct. Pretty sure these builds wouldn't retain any info from previous. 

An alternative to building the whole viz (if that is limiting) would be a travis job that runs a set of checks that confirms the make would work if run (e.g., all referenced `id`s have targets that specify how they are created).

**Comment by aappling-usgs** [comment]
Travis actually supports [caching of arbitrary directories](https://docs.travis-ci.com/user/caching/#Arbitrary-directories), though each new build has to download that cache from one part of Travis into another, so it's not as fast as a local cache. And Travis can definitely cache R packages. I wonder if that would be enough of a time savings to make this practical.

Introducing Travis caching would bring its own complexities, of course, so we'd also want to consider the costs of developing and debugging that implementation, and then fixing problems that arise when there's something cached that we wanted to be overwritten.

Alternatively, yes, maybe we could think of a useful partial build... @jread-usgs, is the example you gave a case you've seen before/repeatedly? (where an ID misspells or fails to reference an existing fetcher/processor/etc.?) If so, another thing we should do is write checks for that into `createMakefiles()` for even speedier feedback.

**Comment by aappling-usgs** [comment]
After more discussion with @wdwatkins , I think that we can close this issue. If a specific need for a partial build arises, I'm happy to add this back, but I don't think we've seen a strong need for it. And the main need - continuous integration and deployment onto a private server so we can preview the results - is well developed in the dev jenkins jobs we've run for recent vizzies.
