### ISSUE TITLE
Documentation- Vignette [3]

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#42]
Create a vignette and complete documentation for the vizlab framework. 

Describe the steps to create a new viz using the package, describe in more detail the viz yaml contents and the purpose, a couple of examples, pull from the climate fish viz as examples. How to run the make. Steps to iterate on a viz. 

Fill out example repo as the psuedo-vignette, a complete but simple implementation of the framework.

**Comment by eread-usgs** [comment]
Check out sbtools or the 2nd geoknife vignette as examples of right-sized documents
This should cover ~ 80% of the use case. Narrative for steps to creating and publishing a rapid viz.

**Comment by lindsaycarr** [comment]
This should get pulled out from README and put into this doc: https://github.com/USGS-VIZLAB/vizlab/pull/53/commits/2b4d263fde5ba27d7eec1660c206efba154eee94

**Comment by eread-usgs** [comment]
Should include section on profile.yaml (per #3) including instructions for how to set up the profile for first time users.

**Comment by lindsaycarr** [comment]
- [ ] overview: what can this package be used for?
- [ ] make workflow: what is make and why is it useful?!
- [ ] setup instructions: vizSkeleton, createProfile, createMakefiles
- [ ] sb authentication **_where should this go in the order?_**
- [ ] what is a viz.yaml?
- [ ] workflow: fetch, read, process, visualize, publish
- [ ] using make
- [ ] example: putting it all together

**Comment by wdwatkins** [comment]
I was thinking just go through the example at the end of each step.

**Comment by wdwatkins** [comment]
#67 work in progress

**Comment by wdwatkins** [comment]
#70 is mostly complete

**Comment by wdwatkins** [comment]
Merged #70, vignette should be finished.  Should be updated though if the example viz is updated, especially the viz.yaml

**Comment by wdwatkins** [comment]
Needs updated to include footer and other new additions

**Comment by eread-usgs** [comment]
Include the viz objects how they get passed into functions.

**Comment by eread-usgs** [comment]
build this into package so it can be found more easily by users.

**Comment by eread-usgs** [comment]
During Matthew, needed quick way to find out to deal w/ dependencies and couldnt find it.

**Comment by wdwatkins** [comment]
Now:
[] viz object passed into all functions
[] footer

pending other issues:
[] multiple dependency management

**Comment by eread-usgs** [comment]
Needs review following recent package modifications.
