### ISSUE TITLE
ability to add feedback form at end of viz

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#46]
See issue created for climate-fish: https://github.com/USGS-VIZLAB/climate-fish-habitat/issues/127

**Comment by aappling-usgs** [comment]
@lindsaycarr and @jread-usgs , what are your thoughts on the ongoing importance of this issue? Do reddit comments and google/usgs analytics answer enough of our questions, or would you still really like to have a feedback form?

**Comment by jread-usgs** [comment]
I personally think this isn't a high priority - as you noted, we are getting feedback elsewhere that I think is honest and often helpful. If we include a form, there are potential issues (paperwork reduction act) that make it more complicated than the implementation. I'd be in favor of closing this.

**Comment by aappling-usgs** [comment]
Works for me - thanks for weighing in. We can always reopen this if it becomes a higher priority.
