### ISSUE TITLE
Create vizlab index page with links to published visualizations

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#50]
This is tied in with wherever we move for hosting, but we want a general page with sitemap that we can point Google to for an additional way to access visualizations.

**Comment by lindsaycarr** [comment]
- [ ] convert js templating to whisker
- [ ] grab context info from viz.yaml for index.html

**Comment by lindsaycarr** [comment]
Part of the way there, but it doesn't look very pretty. Run `publishLandingPage()` and then look at the `index.html` sitting in `output/`

**Comment by jiwalker-usgs** [comment]
To generate full html content, you'll probably want to use fullPage.mustache and use the two parts as `section` types.  You can bring in the css by defining it as a `resource` with packaging = `vizlab`.  The page will be missing some pieces (semantics adds quite a bit to requirements), so that will need to be pulled in from somewhere, or hardcoded into the publishLandingPage script.

Also, once this is done some of the pieces from `inst/landing` can be removed.  You will also likely run into a conflict with the naming of the css file, so renaming it to landing.css is probably smart.

**Comment by lindsaycarr** [comment]
Still need:
- [ ] to fit this page in w/ OWI header/footers
- [ ] great-lakes + climate-fish viz need "thumbnail" specified in viz.yaml info section
- [ ] climate-fish viz needs updated description

**Comment by wdwatkins** [comment]
Looks like the tests are creating a landing directory in `tests/testthat` that should be getting deleted.

**Comment by wdwatkins** [comment]
see #83

**Comment by lindsaycarr** [comment]
@mwernimont some style
@jiwalker-usgs CI
