### ISSUE TITLE
content footer for vizlab

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#54]
- [x] templated footer

- [x] add some links to our group and prior visualizations. Related blogs, visualizations, vizlab logo and index page, may to owi.

**Comment by lindsaycarr** [comment]
convert js to whisker grab info from somewhere... @jiwalker-usgs needs to add some more detail

**Comment by wdwatkins** [comment]
#63 seems to have addressed some/most of this?

**Comment by jiwalker-usgs** [comment]
yeah, that is the content, but we need a way to pull it into a viz.

**Comment by wdwatkins** [comment]
So a mustache template and publisher for viz.yaml section?

**Comment by lindsaycarr** [comment]
yes, I believe that is what is needed. See the landing page work for an example (though it's not perfect yet).

**Comment by wdwatkins** [comment]
Is that #50 ?

**Comment by lindsaycarr** [comment]
yep!

**Comment by wdwatkins** [comment]
Footer is functional now, just need to deal with turning off/on related blogs
