### ISSUE TITLE
Export drupal-ready press release or press release component

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#55]
For example, to be added into the new PR Drupal: https://www.usgs.gov/news/widespread-plastic-pollution-found-great-lakes-tributaries

**Comment by eread-usgs** [comment]
We will bring this up in our meeting w/ OCAP this fall.

**Comment by aappling-usgs** [comment]
@eread-usgs - any updates on this?
* Is this feature still a good idea for vizlab?
* Is this a near-term need? If not, when is this functionality likely to become important?
* Are those Drupal requirements now available somewhere on the web or in your notes?

**Comment by eread-usgs** [comment]
I think the Drupal platform OCAP has developed does not accept embedded graphics, like we produce. I can bring it up as a request later on. In the mean time, we can close this @aappling-usgs

**Comment by aappling-usgs** [comment]
Thanks, @eread-usgs !
