### ISSUE TITLE
need a place for <noscript>

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#57]
For 508 compliance, there needs to be a message that appears when Javascript is turned off. Should go somewhere in fullPage.mustache, but where?

Example with climate-fish-viz: https://github.com/USGS-VIZLAB/climate-fish-habitat/pull/163/commits/8da4b1d2f026dd93639ff983c189ec34702822c5

**Comment by jiwalker-usgs** [comment]
I guess this was fixed with #87
