### ISSUE TITLE
Make analytics a first class citizen [2]

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#7]
Analytics should be simple to add without digging into the javascript much or at all.  Analytics goals should be described so they can be tested as viz is released (i.e. 85% of users make it to the footer).

**Comment by jiwalker-usgs** [comment]
pattern we came up with for climate fish viz was page analytics, section(chapter) analytics, and figure analytics that can hopefully be worked in here.

**Comment by eread-usgs** [comment]
We set up this pattern, whether we like it or not, we should build... there are more analytics types there we want to support initially. Use a JSON string as the event label, which is how we stick in analytics data.
