### ISSUE TITLE
add CO and CA drought vizzies to VIZLAB (1) 

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/vizlab#74]
- [x] Migrate repos for our first visualizations into our VIZLAB repo. 
- [x] Create fake viz.yamls for each that have the required information for the landing page (id, name, description, path, thumbnail)

**Comment by wdwatkins** [comment]
I uploaded thumbnails for both

**Comment by eread-usgs** [comment]
Last step is to transfer ownership of CO and CA drought repos to VIZLAB. Then a couple steps of cleanup: change relative vs absolute paths.

**Comment by jread-usgs** [comment]
I won't be able to do this because I am not an admin on those two vizzies. @jiwalker-usgs assigning to you because I think you are.

**Comment by jiwalker-usgs** [comment]
Do we want to rename CIDA-Viz to ca_drought or something better, or leave as is?
