### ISSUE TITLE
profile.yaml in wrong place from createProfile() on windows (1)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#81]
`createProfile()` puts `profile.yaml` in `C:\Users\aappling\Documents\.vizlab`, but my shell looks for the profile in `C:\Users\aappling\.vizlab`. It's the difference between RStudio's and make's idea of `~`. I had to move it manually to get `make` to run.

**Comment by aappling-usgs** [comment]
also, once i've moved it to where it needs to be for `make`, i get
```r
> createMakefiles()
Error in findProfileYaml() : 
  profile.yaml does not exist in a supported directory. See createProfile().
```

**Comment by eread-usgs** [comment]
Make sure the solution is supported on mac, linux and windows.

**Comment by aappling-usgs** [comment]
I think the truly optimal approach would be to become smarter about the differing values of $HOME in RStudio and bash, and to use that info to create and/or search for this file in the right place. But I've tried and don't see how to do that cleanly, so both #107 and #108 take the more expedient approach of giving the user control in `createProfile()` over where profile.yaml gets written. Probably fine for the next year or two.
