### ISSUE TITLE
clarify/refine script dependencies

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/vizlab#82]
## Problem statement

The current default is for a new viz.yaml object to depend (in its makefile block) on the corresponding scripts directory. e.g., 

``` yaml
  -
    id: matthew-sites
    location: cache/sites_geo.rds
    processor: sites
    reader: rds
    depends: ["sites-data","matthew-counties"]
```

gets this makefile block:

``` make
matthew-sites: cache/sites_geo.rds
cache/sites_geo.rds: cache/sites.rds cache/matthew-counties.rds scripts/process
    export R_LIBS_USER=$(RLIBSUSER);\
    ${RBATCH} "--args fun=process funargs=list(viz='matthew-sites') scripts=c('scripts/process')" \
    vizlab/make/callFunction.R vizlab/make/log/process/matthew-sites.Rout
```

(see the dependency on `scripts/process`?)

But this has two problems:
1. If the specific processor script already exists but then is changed (in this case it's `process.sites.R`), make won't notice and won't rebuild.
2. If a new script is added to the directory, even if the scripts and data related to this item are unchanged, this item will be rebuilt.
## User-based solution

It's already possible to specify the dependency more precisely. You need to add a line to the viz.yaml so the block looks like this:

``` yaml
  -
    id: matthew-sites
    location: cache/sites_geo.rds
    processor: sites
    scripts: scripts/process/process.sites.R
    reader: rds
    depends: ["sites-data","matthew-counties"]
```

and then the make block will look like this:

``` make
matthew-sites: cache/sites_geo.rds
cache/sites_geo.rds: cache/sites.rds cache/matthew-counties.rds scripts/process/process.sites.R
    export R_LIBS_USER=$(RLIBSUSER);\
    ${RBATCH} "--args fun=process funargs=list(viz='matthew-sites') scripts=c('scripts/process/process.sites.R')" \
    vizlab/make/callFunction.R vizlab/make/log/process/matthew-sites.Rout
```

Everybody's user instinct turns out to be to not specify scripts, which means you can type the viz.yaml faster but the above problems of making to seldom and/or too often occur, without any indication from vizlab about why that might be happening. I think we can do better.
## vizlab-based solution[s]

These are options. It's possible that only some of them should be implemented.
1. Vizlab could throw a warning anytime the default (the directory) gets used for `scripts`. Then there would be reminders/incentive to specify the script dependencies in the viz.yaml.
2. We could remove the default and require a script to be specified every time.
3. We could change the default to be exactly the script implied by the processor (e.g., scripts/process/process.sites.R in the above example). The past and current vizlab developers should talk this through to see whether the proposed default script is usually the right one, and what to do when a canned reader/processor/fetcher/etc. is used (e.g., `vizlab:::readData.rds`).
4. If we choose number 3, we should think about whether to also include the whole `scripts/process` directory as an additional dependency (this biases us toward remaking too often) or leaving it out (this biases us toward accidentally omitting helper scripts from the dependencies list). I'm currently leaning toward leaving it out.
5. If in number 4 we choose to leave out the directory dependency, we could possibly add some smart checks somewhere in `createMakefiles()` to notice any calls to `source()` within the scripts that are depended on, and to give a warning if the sourced file isn't included as a dependency in viz.yaml.

**Comment by eread-usgs** [comment]
For now, we will go with the user-based solution, and @aappling-usgs we'd like you to add the warning, per (1) above. We will revisit this issue more holistically at a later date. 

Comment in discussion: How many of these issues would be resolved by using remake?

**Comment by aappling-usgs** [comment]
I've been working on adding the warning per (1). To make the warning visible to users during the usual workflow (`make`ing things at the command prompt), I've added the warnings to the makefiles. They can get updated anytime the makefile gets updated, which is anytime viz.yaml gets updated, which I think is the appropriate frequency given that users will need to edit viz.yaml to reduce the number of warnings.

Here's an example of a call to `make` with warnings for `inst/testviz`:
```sh
$ make
make -f vizlab/make/fetch.make
make[1]: Entering directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizz
ies/vizlab/inst/testviz'
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetchTimestamp funargs=list(viz='siteTextData') scri
pts=c('scripts/fetch')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/siteTextData_timestamp.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetch funargs=list(viz='siteTextData') scripts=c('sc
ripts/fetch')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/siteTextData.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetchTimestamp funargs=list(viz='MayflyNymph') scrip
ts=c('scripts/fetch/mayflyNymph.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/MayflyNymph_timestamp.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetch funargs=list(viz='MayflyNymph') scripts=c('scr
ipts/fetch/mayflyNymph.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/MayflyNymph.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetchTimestamp funargs=list(viz='carData') scripts=c
('scripts/fetch')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/carData_timestamp.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=fetch funargs=list(viz='carData') scripts=c('scripts
/fetch')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/carData.Rout

-----WARNING-----
Script dependencies should be specific files to avoid Making items too seldom or
 too often. You can override the default (a directory) by setting 'scripts' in e
ach viz.yaml item.
* Items depending on the scripts/fetch directory: fetch/siteTextData, fetch/Cuya
hoga, fetch/carData
-----------------

make[1]: Leaving directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizzi
es/vizlab/inst/testviz'
make -f vizlab/make/process.make
make[1]: Entering directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizz
ies/vizlab/inst/testviz'

process.make looks OK!

make[1]: Leaving directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizzi
es/vizlab/inst/testviz'
make -f vizlab/make/visualize.make
make[1]: Entering directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizz
ies/vizlab/inst/testviz'

-----WARNING-----
Script dependencies should be specific files to avoid Making items too seldom or
 too often. You can override the default (a directory) by setting 'scripts' in e
ach viz.yaml item.
* Items depending on the scripts/visualize directory: visualize/relativeAbundanc
eFig
-----------------

make[1]: Leaving directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizzi
es/vizlab/inst/testviz'
make -f vizlab/make/publish.make
make[1]: Entering directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizz
ies/vizlab/inst/testviz'
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=publish funargs=list(viz='index')" \
vizlab/make/callFunction.R vizlab/make/log/publish/index.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=publish funargs=list(viz='relativeAbundance')" \
vizlab/make/callFunction.R vizlab/make/log/publish/relativeAbundance.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=publish funargs=list(viz='footer')" \
vizlab/make/callFunction.R vizlab/make/log/publish/footer.Rout
export R_LIBS_USER="C:/Users/aappling/Documents/R/win-library/3.3";\
"C:/Program Files/R/R-3.3.2/bin/x64/R.exe" CMD BATCH --no-timing --quiet --no-sa
ve --no-restore "--args fun=publish funargs=list(viz='footer-style')" \
vizlab/make/callFunction.R vizlab/make/log/publish/footer-style.Rout

publish.make looks OK!

make[1]: Leaving directory `/cygdrive/c/Users/aappling/Documents/GitHub/DS Vizzi
es/vizlab/inst/testviz'
```

the new bits are the `-----WARNING-----` and `xxxx.make looks OK!` sections.

**Comment by aappling-usgs** [comment]
An issue we'll notice almost immediately is that items like `fetch/siteTextData`, `fetch/Cuyahoga`, and `fetch/carData` use vizlab functions and therefore don't need any scripts at all. A user might think that not setting a value for `scripts:` at all in the viz.yaml would work, but it won't. You'll actually need to set it to a blank value to get rid of the warning.

One possible response to this is to make a note of it, as I've just done.

Another is to change the default from being the directory that corresponds to the block (e.g., scripts/fetch) to being blank, more like solution (2) proposed above. I'm OK with that, too, but going to stick to the original scope (just implementing (1)=warning) unless & until we agree that more is needed.
