### ISSUE TITLE
Allow fetch to depend on process item

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#88]
All fetch targets happen before all process targets, then visualize, then publish.  At the very least fetch should be able to depend on a process step (eg. fetch some map data, process to get bounding box, then fetch more data based on bounding box query).

**Comment by ldecicco-USGS** [comment]
Also, it would be great to have global variables. For example, states, start.date, and end.date was required to be defined in at least 3 different places in the yaml.

**Comment by aappling-usgs** [comment]
this could be related to the problem laura is seeing with dependencies of some publish steps on files provided by the vizlab package - see new issue about to be created.

**Comment by aappling-usgs** [comment]
PR #281 creates a single remake.yaml for all of the blocks, and looks for cross references in any phase (not just the current one). That might be all we need to resolve this issue, but we should also do some testing before closing this.

**Comment by aappling-usgs** [comment]
closed by #316, e741f14
