### ISSUE TITLE
Create tag for each level of figure complexity

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#9]
To come up a "good enough" figure while having the chance to end up with an "out of the park" figure in the end we will need a mechanism to sandbox and swap these in with minimal overhead.  One possibility is both figures live in the output directory (built, perhaps not deployed) with a different tag, and the one included in the viz is that which is closest to "releasable" at the moment (decided in layout).

**Comment by aappling-usgs** [comment]
feature branches?

**Comment by jiwalker-usgs** [comment]
I think that would be a reasonable way to achieve this, but handling many concurrent changes across several branches might be hard to manage.  I find a single dev branch with feature toggles to be more palatable in this case, but I'd like to hear others' thoughts.

**Comment by aappling-usgs** [comment]
fair enough. i agree that switching branches is a pain if you plan to do it more than 1-2 times.

**Comment by jiwalker-usgs** [comment]
That and I'm thinking these might be longer running branches that could be hard to merge back in when they are done.

**Comment by aappling-usgs** [comment]
I have not seen a major need for this over the last year. We have successfully used collaborative design meetings, feature branches, and even chunks of code in the main repo that don't ultimately lead to published figures. This has all seemed OK, so until/unless we arrive at a clear and present need for this feature, I think we can close this issue.
