### ISSUE TITLE
Using dependencies from viz.yaml (2)

### ISSUE THREAD

**Issue by jiwalker-usgs** [USGS-VIZLAB/vizlab#92]
The `viz[['depends']]` needs a bit of love to make it work for the script pattern we have.  Currently there are two ways to access something from depends:

``` r
process.timeAndMap <- function(viz) {
  timeData <- readData(viz[['depends']][1])
  mapData <- readData(viz[['depends']][2])
}
```

or if yaml looks like

``` yaml
-
  id: myProcess
  processor: timeAndMap
  depends: [ "firstDependency", "myDependency" ]
  timeData: firstDependency
  mapData: myDependency
```

then script can do something like:

``` r
process.timeAndMap <- function(viz) {
  timeData <- readData(viz[['timeData']])
  mapData <- readData(viz[['mapData']])
}
```

neither are very satisfying, as well as needing to call readData from script rather than having it at the ready.  So a couple topics of discussion:
1. Should we switch depends to a named list so code ends up looking like second script without duplication of ids?
2. Should data be read in automatically so script does not need to call `readData()` directly? (I don't think this is the main issue, but worth discussing)
3. Do we want to formalize in some way the second approach that the depends section isn't even required? (I'm thinking here maybe we replace all references with a sigil that denotes a dependency so we can still build our dependency graph; this would look something like `@id`, `&id`, or `!id`).
4. Are there other things here that I'm missing, what is the natural approach for using dependencies?

**Comment by jread-usgs** [comment]
Maybe a bad idea (although not sure why), but what about keeping the dependencies with the code somehow and leaving them out of the yaml, kind of like `#' @importFrom pkg fnc`

something like 
```
myfun <- function(viz){
    depends("firstDependency", "myDependency")
    time.range <- range(firstDependency)
    return(time.range)
}

**Comment by aappling-usgs** [comment]
Agreed, @jread-usgs - I like the idea of keeping dependencies with the code wherever possible.

Something that I haven't fully understood is why the `viz[['depends']][1]` paradigm rose to the top. Would you do it differently if I told you that
```r
pd <- readData('precip-data')
```
also works? When I was sketching out pieces of vizlab this summer I had something more like this in mind:
```r
processData.mungePrecip <- function(viz, precip_data=readData('precip-data')) {
  ...code using precip_data...
}
```

you still currently have to copy the dependencies from the function argument list over to viz.yaml (maybe that could be fixed) but even now I think I'd find it easier to use names in both places rather than using dependency indices within the function.

**Comment by aappling-usgs** [comment]
see also #94 and #82

**Comment by ldecicco-USGS** [comment]
```
  id: myProcess
  processor: timeAndMap
  depends: [ 
        - timeData: "firstDependency"
        - mapData: "myDependency" ]
```

**Comment by eread-usgs** [comment]
This *might* just work!

**Comment by eread-usgs** [comment]
1) can use what @jiwalker-usgs  showed in top comment. 
2) can try what @ldecicco-USGS showed in comment 2 up from this
2a) Might need a little function to get the depends back into the vector

**Comment by eread-usgs** [comment]
@wdwatkins will try 2) and 2a) first.

**Comment by wdwatkins** [comment]
I think it is just working 🎉 
>id: matthew-flowlines
    location: cache/matthew-flowlines.rds
    processor: flowlines
    scripts: scripts/process/process.flowlines.R
    reader: rds
    depends: 
        flow: "flowlines"
        counties: "matthew-counties"

>counties <- readData(viz[['depends']]$counties)
  flowlines <- readData(viz[['depends']]$flow)

I think we'll only need to do this when there are multiple depends that need to be referenced by name inside a function.  It shouldn't matter in the publish sections when all the dependencies just need to be there.

**Comment by wdwatkins** [comment]
☝️ note that the indent for the two depends is getting erased by github
![image](https://cloud.githubusercontent.com/assets/13987349/20448400/5a98003c-ada9-11e6-8306-b15ea777ff8a.png)

**Comment by wdwatkins** [comment]
Would be good to test this more though to be sure

**Comment by aappling-usgs** [comment]
example illustrating jread's comment at https://github.com/USGS-VIZLAB/water-use/pull/17#discussion_r90333807, about an issue that i also find confusing:

`viz.yaml`:
```
process:
  -
    id: calc-waterData
    location: cache/wuClean.rds
    ...etc...
visualize:
  -
    id: wuBars
    depends: 
      waterUse: calc-waterData
    ...etc...
```

the names that get assigned are the right-hand sides, and the viz IDs that get read are the right-hand sides. that seems strange to me - what's the point of the secondary IDs if they get ignored by readDepends?
```r
viz <- getContentInfo('wuBars')
deps <- readDepends(viz)
names(deps)
[1] "calc-waterData"
```

it's also confusing because if i wanted to use readData instead of readDepends, i'd refer to the other id:
```r
wu1 <- readData(viz[['depends']][['waterUse']])
wu2 <- readDepends(viz)$'calc-waterData'
all.equal(wu1, wu2)
## TRUE
```
`wu1` and `wu2` are the same, but i've had to refer to them by different IDs. is that really what we want?

**Comment by ldecicco-USGS** [comment]
Well, I for one had never heard of the function `readDepends` until today. I don't really care if we name the depends arguments in the viz.yaml for using `readData`, or don't and use `readDepends`. As long as I never again have to count and re-count what argument in depends I'm trying to use.

**Comment by jiwalker-usgs** [comment]
yeah, I think you are right, this seems backwards and I didn't look at it close enough.  The correct usage should be (for this example):
```r
wu2 <- readDepends(viz)[['waterUse']]
```

at least that's how it is in my head

**Comment by ldecicco-USGS** [comment]
ohh...that's another handy looking function `getContentInfo`!

**Comment by jiwalker-usgs** [comment]
yeah, the internal documentation might not lead you to some of these functions

**Comment by wdwatkins** [comment]
Was this ever addressed?

**Comment by jiwalker-usgs** [comment]
I think it can be called done, it will come up again if we aren't handling this right.
