### ISSUE TITLE
Embeddable figures out of Vizlab (2)

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/vizlab#97]
Re-think this. object instead? SVG crowbar?

**Comment by eread-usgs** [comment]
- [ ] Add a property to the figures (or sections?) to make them embeddable. Then, in the publish phase, figures will get published in two places. 

- [ ] In the UI, have an Icon and popup that gives the text to copy to embed

**Comment by mwernimont** [comment]
![embed-01](https://cloud.githubusercontent.com/assets/6390096/23263459/f03ffe82-f9a3-11e6-99ce-33a14e4030a5.png)
![embed-02](https://cloud.githubusercontent.com/assets/6390096/23263463/f23ab2cc-f9a3-11e6-8280-93aba961fd1e.png)

**Comment by mwernimont** [comment]
I woulda uploaded an SVG but GitHub doesn't accept that file type. But what do you think of either of these @jiwalker-usgs?  Got any other ideas that portray embedding?

**Comment by mwernimont** [comment]
Also they can be any color we want, just using black and white for simplicity

**Comment by jiwalker-usgs** [comment]
I like it (probably prefer the second).  Do you have a preferred dialog method after they click to embed (model, popup, expanded div)?

**Comment by mwernimont** [comment]
probably a model or popup with the code in it. I like the code to only be around when we need it and not cluttering the file.

**Comment by aappling-usgs** [comment]
Closing this issue so the torch can be carried on by #188
